### PR TITLE
Elasticsearch use numerical indexes for rollover

### LINKED ISSUE #104: Elasticsearch index naming causing problems for rollover
**Goal:** Easier data management

Raised by Hjalti at Decode.
When trying to setup rollover of data Elasticsearch errors.

> One thing I forgot to ask you is how you recommend creating a index policy lifecycle in Elasticsearch.
>It seems to fail doing the rollover, I know this is not Mistral related but since you are using Elasticsearch I wanted to know how you are doing this.
```java
Illegal_argument_exception: index.lifecycle.rollover_alias [mistral] does not point to index [mistral-2020-11-17]
```

### PR DESCRIPTION
**Pull request by liamellexus**
Fixes #104 

Also defaults the curl schema creation script to ignore self signed certificate errors when using SSL.

- [x] Development complete
- [x] Documentation complete
- [ ] Test case added
- [x] Version number updated
- [x] Representative testing complete
- [ ] Full testing complete

### CODE REVIEW

File: output/mistral_elasticsearch/schema/mistral_create_elastic_template.sh [hunk 1]
```diff
@@ -124,6 +129,13 @@ function main() {
             --user=*)
                 username="${1#--user=}"
                 ;;
+            -d | --date)
+                format="date"
+                ;;
+            --date=*)
```
Comment (nick-ellexus) [inline output/mistral_elasticsearch/schema/mistral_create_elastic_template.sh:135]: This will accept --date=no, among other things. Do we want that?

**Review by nick-ellexus — CHANGES_REQUESTED** [review]
Broadly OK, but I think your use of getopt_long isn't quite right. Also you could reduce duplicated code in the error cases.
